name: discord
base: core18
adopt-info: discord
summary: Free voice and text chat
description: |
 All-in-one voice and text chat for gamers that's free, secure, and
 works on both your desktop and phone. Stop paying for TeamSpeak
 servers and hassling with Skype. Simplify your life.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  discord:
    plugin: dump
    source: "https://discordapp.com/api/download?platform=linux&format=deb"
    source-type: deb
    override-build: |
      snapcraftctl build
      DEB_API="https://discordapp.com/api/download?platform=linux&format=deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f6)
      snapcraftctl set-version $(echo $VERSION)
      # Correct path to icon.
      sed -i 's|Icon=discord|Icon=/usr/share/discord/discord\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/discord/discord.desktop
    build-packages:
      - curl
      - sed
    stage-packages:
      - libasound2
      - libatomic1
      - libc++1
      - libgconf2-4
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open
  cleanup:
    after: [ discord ]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  discord:
    extensions: [gnome-3-34]
    command: usr/share/discord/Discord
    desktop: usr/share/applications/discord.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - bluez
      - browser-support
      - camera
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-observe
      - unity7
      - wayland
      - x11
